version: "3"

services:
  postgres:
    image: postgres:13.8
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: testpass
    volumes:
      - url_postgres_data:/var/lib/postgresql/data

volumes:
  url_postgres_data: 

